/*        Generated by TAPENADE     (INRIA, Tropics team)
    Tapenade 3.7 (r4781) - 21 Feb 2013 13:50


  Differentiation of rosenbrock in forward (tangent) mode:
   variations   of useful results: *f
   with respect to varying inputs: x[_:_]
   RW status of diff variables: *f:out x[_:_]:in
   Plus diff mem management of: f:in x:in
*/

long double rosenbrock(double x[], int n)
{
  int i;
  long double f = 0.0;

  for (i = 0; i < n-1; ++i) {
      f = f + 100*(x[i]*x[i]-x[i+1])*(x[i]*x[i]-x[i+1]) + (x[i]-1)*(x[i]-1
          );
  }

  return f;
}

long double rosenbrock_gradient(double x[], double xd[], int n) {
    int i;
    long double fd = 0.0;

    for (i = 0; i < n-1; ++i) {
        fd = fd + 100*((xd[i]*x[i]+x[i]*xd[i]-xd[i+1])*(x[i]*x[i]-x[i+1])) +
            100*((x[i]*x[i]-x[i+1])*(xd[i]*x[i]+x[i]*xd[i]-xd[i+1])) + xd[i]*(
            x[i]-1) + (x[i]-1)*xd[i];
    }

    return fd;
}
